### ISSUE TITLE
Black cutscenes

### ISSUE THREAD

**Issue by ArchieMeng** [TodokanaiTL/wa2-wine#1]
Operating System: Arch Linux 5.2.14-zen2
CPU: i7 7500U
GPU: Intel HD Graphics 620
Wine version: 4.15
winetricks dlls: lucida corefonts cjkfonts devenum d3dx9 quartz wmp9 
Description:
Game cutscenes are black but with sounds.
And I am using a fresh win32 wine installation.
Another thing I noticed is that I cannot play the wmv game videos by WMP. WMP9 will always crash when trying to play them.
The game video files are integrated, and can be successfully played by vlc even within wine.

**Comment by ObserverOfTime** [comment]
I swear every time I get it working it just breaks again...

**Comment by ArchieMeng** [comment]
So, how do you get it working? Maybe it's a bug of wine?🤣

**Comment by ObserverOfTime** [comment]
VLC works because it has its own codecs. WA2 defers to WMP which, for whatever reason, doesn't work most of the time. Installing extra codecs has never worked for me either.

**Comment by ObserverOfTime** [comment]
I also tried using GStreamer instead of WMP, but that doesn't work either.
`gst-launch-1.0-32` detects the correct format of the video and runs it without issue:
```
video/x-wmv, wmvversion=(int)3, format=(string)WMV3, width=(int)1280, height=(int)720, codec_data=(buffer)4ff1080100, framerate=(fraction)10000000/333667
```
However, `winegstreamer` somehow detects it incorrectly and doesn't work.
```
video/x-wmv, wmvversion=(int)2, width=(int)1280, height=(int)720, codec_data=(buffer)efd0b480, pixel-aspect-ratio=(fraction)1/1, format=(string)WMV2, framerate=(fraction)25/1
```
(Even after converting the video to WMV2 it still fails to work.)

**Comment by ArchieMeng** [comment]
> I also tried using GStreamer instead of WMP, but that doesn't work either.
> `gst-launch-1.0-32` detects the correct format of the video and runs it without issue:
> 
> ```
> video/x-wmv, wmvversion=(int)3, format=(string)WMV3, width=(int)1280, height=(int)720, codec_data=(buffer)4ff1080100, framerate=(fraction)10000000/333667
> ```
> 
> However, `winegstreamer` somehow detects it incorrectly and doesn't work.
> 
> ```
> video/x-wmv, wmvversion=(int)2, width=(int)1280, height=(int)720, codec_data=(buffer)efd0b480, pixel-aspect-ratio=(fraction)1/1, format=(string)WMV2, framerate=(fraction)25/1
> ```
> 
> (Even after converting the video to WMV2 it still fails to work.)

Ok, thx. I guess I might manually watch the cutscenes by opening them by myself instead of watching the game built-in ones now. hhhhh

**Comment by ObserverOfTime** [comment]
You could submit a bug report on the wine tracker, but don't expect anything.

**Comment by fallenguru** [comment]
One more data-point: Running the [体験版](https://leaf.aquaplus.jp/product/wa2ic/special_trial.html) through [Proton GE](https://github.com/GloriousEggroll/proton-ge-custom) 5.6-GE-2, *without any further tweaks*, results in perfectly working videos -- in windowed mode. In fullscreen mode there's only sound. If a video starts in windowed mode, it will continue running correctly when switching to fullscreen mode, if it starts in fullscreen mode, it will start working as soon as the game's switched back to windowed.

**Comment by Binary-Eater** [comment]
I sort of gave up on trying to have a reasonable workflow when it came to dealing with ASF.

https://github.com/Binary-Eater/WhiteAlbum2-Proton-patch-scripts?tab=readme-ov-file#white-album-2s-use-of-microsoft-advanced-streaming-format-asf-videox-ms-asf
